### ISSUE TITLE
Is there sample project?

### ISSUE THREAD

**Issue by itome** [sunaokumura/react-native-payjp#2]
iOSに関して、この部分がうまく行きませんでした。サンプルプロジェクトなどありますか？

> iOSの場合は、続いてXcodeでReactNativeのプロジェクトファイルを開いて プロジェクトに空のswiftファイルとbridging-headerを追加してください。 これはSwiftで書かれているPAYJPのライブラリを実行するために Swift標準ライブラリをアプリに組み込むためです。

**Comment by sunaokumura** [comment]
@itome こんにちは。サンプルプロジェクトありません。今はMacを持っていないのでサンプルプロジェクトも作れません。
ごめんなさい。

**Comment by itome** [comment]
わかりました。対応ありがとうございます。
